/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LacakRouteImport } from './routes/lacak'
import { Route as JokiRouteImport } from './routes/joki'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JokiIndexRouteImport } from './routes/joki.index'
import { Route as TopupSlugRouteImport } from './routes/topup.$slug'
import { Route as JokiSlugRouteImport } from './routes/joki.$slug'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LacakRoute = LacakRouteImport.update({
  id: '/lacak',
  path: '/lacak',
  getParentRoute: () => rootRouteImport,
} as any)
const JokiRoute = JokiRouteImport.update({
  id: '/joki',
  path: '/joki',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JokiIndexRoute = JokiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JokiRoute,
} as any)
const TopupSlugRoute = TopupSlugRouteImport.update({
  id: '/topup/$slug',
  path: '/topup/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JokiSlugRoute = JokiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JokiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/joki': typeof JokiRouteWithChildren
  '/lacak': typeof LacakRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/joki/$slug': typeof JokiSlugRoute
  '/topup/$slug': typeof TopupSlugRoute
  '/joki/': typeof JokiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/lacak': typeof LacakRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/joki/$slug': typeof JokiSlugRoute
  '/topup/$slug': typeof TopupSlugRoute
  '/joki': typeof JokiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/joki': typeof JokiRouteWithChildren
  '/lacak': typeof LacakRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/joki/$slug': typeof JokiSlugRoute
  '/topup/$slug': typeof TopupSlugRoute
  '/joki/': typeof JokiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/joki'
    | '/lacak'
    | '/privacy'
    | '/terms'
    | '/update-password'
    | '/joki/$slug'
    | '/topup/$slug'
    | '/joki/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/lacak'
    | '/privacy'
    | '/terms'
    | '/update-password'
    | '/joki/$slug'
    | '/topup/$slug'
    | '/joki'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/joki'
    | '/lacak'
    | '/privacy'
    | '/terms'
    | '/update-password'
    | '/joki/$slug'
    | '/topup/$slug'
    | '/joki/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  JokiRoute: typeof JokiRouteWithChildren
  LacakRoute: typeof LacakRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  TopupSlugRoute: typeof TopupSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lacak': {
      id: '/lacak'
      path: '/lacak'
      fullPath: '/lacak'
      preLoaderRoute: typeof LacakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joki': {
      id: '/joki'
      path: '/joki'
      fullPath: '/joki'
      preLoaderRoute: typeof JokiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joki/': {
      id: '/joki/'
      path: '/'
      fullPath: '/joki/'
      preLoaderRoute: typeof JokiIndexRouteImport
      parentRoute: typeof JokiRoute
    }
    '/topup/$slug': {
      id: '/topup/$slug'
      path: '/topup/$slug'
      fullPath: '/topup/$slug'
      preLoaderRoute: typeof TopupSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joki/$slug': {
      id: '/joki/$slug'
      path: '/$slug'
      fullPath: '/joki/$slug'
      preLoaderRoute: typeof JokiSlugRouteImport
      parentRoute: typeof JokiRoute
    }
  }
}

interface JokiRouteChildren {
  JokiSlugRoute: typeof JokiSlugRoute
  JokiIndexRoute: typeof JokiIndexRoute
}

const JokiRouteChildren: JokiRouteChildren = {
  JokiSlugRoute: JokiSlugRoute,
  JokiIndexRoute: JokiIndexRoute,
}

const JokiRouteWithChildren = JokiRoute._addFileChildren(JokiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  JokiRoute: JokiRouteWithChildren,
  LacakRoute: LacakRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  TopupSlugRoute: TopupSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
